version: "3.9"

services:
  # PostgreSQL (write DB)
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MongoDB (read DB)
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Kafka (KRaft mode, no Zookeeper)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /kafka/kraft-combined-logs
    volumes:
      - kafka_data:/kafka

  # Order service
  order-service:
    build: ./src/services/order
    container_name: order-service
    restart: unless-stopped
    env_file:
      - ./.env

    depends_on:
      - postgres
      - mongo
      - kafka
    ports:
      - "3001:3001"

  # Product service
  product-service:
    build: ./src/services/product
    container_name: product-service
    restart: unless-stopped
    env_file:
      - ./.env

    depends_on:
      - postgres
      - mongo
      - kafka
    ports:
      - "3002:3002"

  # Payment service
  payment-service:
    build: ./src/services/payment
    container_name: payment-service
    restart: unless-stopped
    env_file:
      - ./.env

    depends_on:
      - postgres
      - mongo
      - kafka
    ports:
      - "3003:3003"

  # User service
  user-service:
    build: ./src/services/user
    container_name: user-service
    restart: unless-stopped
    env_file:
      - ./.env

    depends_on:
      - postgres
      - mongo
      - kafka
    ports:
      - "3004:3004"

volumes:
  postgres_data:
  mongo_data:
  kafka_data:
